deploy-to-server:
  stage: deploy
  only:
    - master
  before_script:
    - whoami
    - REPOSITORY=/home/ubuntu/tumo
    - PROJECT_NAME=S05P13A302
    - echo '배포 시작'
  script:
    - cd $REPOSITORY/$PROJECT_NAME/
    - git pull origin master
    - cd ..
    - sudo ./deploy.sh
  after_script:
    - echo '배포 완료'
  tags:
    - deploy